import AppKit

/// Decides whether a pasteboard change is allowed to be recorded.
///
/// This is the privacy gate: secret and transient content, and content from
/// blocked applications, must never reach the history store.
struct PasteboardFilter {
    /// Pasteboard types that mark content as secret or transient. Standard
    /// `org.nspasteboard.*` hints are honored so password managers and similar
    /// tools can opt out of history.
    static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    /// Bundle identifiers of apps whose clips should be ignored.
    var blockedBundleIDs: Set<String>

    init(blockedBundleIDs: Set<String> = []) {
        self.blockedBundleIDs = blockedBundleIDs
    }

    /// Returns `true` when a pasteboard change with the given `types` from the
    /// app identified by `sourceBundleID` is allowed to be stored.
    func shouldStore(types: [NSPasteboard.PasteboardType], sourceBundleID: String?) -> Bool {
        let rawTypes = Set(types.map(\.rawValue))
        if !rawTypes.isDisjoint(with: Self.excludedTypes) { return false }
        if let sourceBundleID, blockedBundleIDs.contains(sourceBundleID) { return false }
        return true
    }
}
