import XCTest
import AppKit
@testable import Copybara

final class PasteboardFilterTests: XCTestCase {
    func testAllowsPlainText() {
        let filter = PasteboardFilter()
        XCTAssertTrue(filter.shouldStore(types: [.string], sourceBundleID: "com.example.app"))
    }

    func testBlocksConcealedType() {
        let filter = PasteboardFilter()
        let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        XCTAssertFalse(filter.shouldStore(types: [.string, concealed], sourceBundleID: nil))
    }

    func testBlocksTransientAndAutoGeneratedTypes() {
        let filter = PasteboardFilter()
        let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        XCTAssertFalse(filter.shouldStore(types: [transient], sourceBundleID: nil))
        XCTAssertFalse(filter.shouldStore(types: [autoGenerated], sourceBundleID: nil))
    }

    func testBlocksBlockedApp() {
        let filter = PasteboardFilter(blockedBundleIDs: ["com.secret.vault"])
        XCTAssertFalse(filter.shouldStore(types: [.string], sourceBundleID: "com.secret.vault"))
        XCTAssertTrue(filter.shouldStore(types: [.string], sourceBundleID: "com.other.app"))
    }
}
